const { Recomendacion } = require('../models');

const DEFAULTS = [
  {
    nombre: 'Horno eléctrico',
    texto: 'Evita abrir el horno durante la cocción de alimentos porque pierde una cantidad de calor considerable (20%) y deberá recuperar con más consumo de energía.',
    aliases: ['horno', 'horno electrico'],
    categoria: 'Cocina',
    potencia_w: 1100,
    horas_uso_dia: 1,
    orden: 1,
  },
  {
    nombre: 'Horno microondas',
    texto: 'Utiliza el horno microondas solo para calentar y no para cocinar.',
    aliases: ['microondas', 'micro'],
    categoria: 'Cocina',
    potencia_w: 800,
    horas_uso_dia: 0.5,
    orden: 2,
  },
  {
    nombre: 'Refrigeradora',
    texto: 'Abre tu refrigeradora solo las veces necesarias, cerrando bien la puerta vamos ahorrando, no introduzcas alimentos calientes.',
    aliases: ['refrigerador', 'refri', 'nevera'],
    categoria: 'Hogar',
    potencia_w: 200,
    horas_uso_dia: 24,
    orden: 3,
  },
  {
    nombre: 'Licuadora',
    texto: 'Utiliza la licuadora en una potencia moderada y picar antes los productos que vas licuar y sobre todo fíjate que las cuchillas no están gastadas.',
    categoria: 'Cocina',
    potencia_w: 500,
    horas_uso_dia: 0.25,
    orden: 4,
  },
  {
    nombre: 'Equipo de sonido',
    texto: 'Desconecta el equipo cuando no lo estés usando, evitemos el consumo en modo stand-by.',
    aliases: ['sonido', 'parlante', 'audio'],
    categoria: 'Entretenimiento',
    potencia_w: 100,
    horas_uso_dia: 2,
    orden: 5,
  },
  {
    nombre: 'Ventilador',
    texto: 'Usa el ventilador en temporadas de extremo calor, además no lo utilices para secar la ropa o cualquier otro material.',
    categoria: 'Climatización',
    potencia_w: 75,
    horas_uso_dia: 6,
    orden: 6,
  },
  {
    nombre: 'Terma eléctrica',
    texto: 'No dejes encendida todo el día tu terma, préndela una hora antes de bañarte, ¡mejor utiliza un temporizador y ahorremos energía!',
    aliases: ['terma', 'calentador de agua'],
    categoria: 'Baño',
    potencia_w: 1500,
    horas_uso_dia: 2,
    orden: 7,
  },
  {
    nombre: 'Ducha eléctrica',
    texto: 'Limite su tiempo de baño al mínimo indispensable, mejor sería cambiarla la ducha eléctrica por una a gas.',
    aliases: ['ducha', 'ducha electrica'],
    categoria: 'Baño',
    potencia_w: 5500,
    horas_uso_dia: 0.25,
    orden: 8,
  },
  {
    nombre: 'Plancha eléctrica',
    texto: 'Plancha primero la ropa gruesa. Apaga la plancha y finaliza con la ropa delgada aprovechando el calor residual.',
    aliases: ['plancha'],
    categoria: 'Lavandería',
    potencia_w: 1200,
    horas_uso_dia: 0.5,
    orden: 9,
  },
  {
    nombre: 'Cocina eléctrica',
    texto: 'Utiliza la cocina eléctrica solo si es necesario, consumes menos energía eléctrica cocinando a gas.',
    aliases: ['cocina', 'anafe electrico'],
    categoria: 'Cocina',
    potencia_w: 2000,
    horas_uso_dia: 1,
    orden: 10,
  },
  {
    nombre: 'Hervidor de agua',
    texto: 'Hierve el agua necesaria y guárdala en un termo, así evitarás usar el hervidor más de una vez al día.',
    aliases: ['hervidor', 'pava electrica'],
    categoria: 'Cocina',
    potencia_w: 1500,
    horas_uso_dia: 0.25,
    orden: 11,
  },
  {
    nombre: 'Tostadora eléctrica',
    texto: 'Mantenla limpia de residuos y desenchúfala cuando no la vayas a usar.',
    aliases: ['tostadora'],
    categoria: 'Cocina',
    potencia_w: 800,
    horas_uso_dia: 0.25,
    orden: 12,
  },
  {
    nombre: 'Olla arrocera',
    texto: 'No la dejes conectada todo el día, desenchúfala cuando termine la cocción.',
    aliases: ['arrocera', 'olla rice cooker'],
    categoria: 'Cocina',
    potencia_w: 700,
    horas_uso_dia: 1,
    orden: 13,
  },
  {
    nombre: 'Waflera',
    texto: 'Utilízala el tiempo necesario y luego desenchúfala.',
    aliases: ['waffle'],
    categoria: 'Cocina',
    potencia_w: 900,
    horas_uso_dia: 0.25,
    orden: 14,
  },
  {
    nombre: 'Cafetera',
    texto: 'Te recomendamos utilizar la cafetera una vez al día, guarda el café en un recipiente y caliéntalo para las demás tomas, más económico será pasar el café gota a gota en las jarras que no utilizan electricidad.',
    categoria: 'Cocina',
    potencia_w: 900,
    horas_uso_dia: 0.25,
    orden: 15,
  },
  {
    nombre: 'Batidora',
    texto: 'Controla el tiempo de uso y luego desenchúfalo.',
    categoria: 'Cocina',
    potencia_w: 300,
    horas_uso_dia: 0.25,
    orden: 16,
  },
  {
    nombre: 'Campana extractora',
    texto: 'Compra el equipo con etiqueta de eficiencia energética y además de una buena elección, si cuando estés cocinando no hay mucho humo, no lo utilices a máxima potencia.',
    aliases: ['campana', 'extractor'],
    categoria: 'Cocina',
    potencia_w: 200,
    horas_uso_dia: 0.5,
    orden: 17,
  },
  {
    nombre: 'Aire acondicionado',
    texto: 'Elige un aparato eficiente, colócalo a una temperatura media (24°C-26°C). Evita usarlo de noche abre las ventanas para mantener el ambiente fresco y reducirás muchas horas de consumo de energía.',
    aliases: ['aire', 'ac', 'minisplit', 'split'],
    categoria: 'Climatización',
    potencia_w: 1000,
    horas_uso_dia: 4,
    orden: 18,
  },
  {
    nombre: 'Televisor',
    texto: 'Utiliza el televisor solo cuando lo veas, si vas a dormir o es cierre del local prográmalo para que se apague automáticamente y mejor desenchúfalo.',
    aliases: ['tv', 'tele', 'television'],
    categoria: 'Entretenimiento',
    potencia_w: 50,
    horas_uso_dia: 6,
    orden: 19,
  },
  {
    nombre: 'Laptop',
    texto: 'Enciéndela cuando la vayas a usar y cárgala solo lo necesario, desconéctala si no la vas a usar.',
    aliases: ['portatil', 'notebook'],
    categoria: 'Informática',
    potencia_w: 65,
    horas_uso_dia: 4,
    orden: 20,
  },
  {
    nombre: 'Computadora',
    texto: 'Apaga la pantalla sino vas a usar la computadora por más de 10 minutos y por completo si es por más de 30 minutos.',
    aliases: ['pc', 'desktop', 'computador'],
    categoria: 'Informática',
    potencia_w: 200,
    horas_uso_dia: 4,
    orden: 21,
  },
  {
    nombre: 'Cargador de celular',
    texto: 'No es necesario cargar el celular toda la noche, desconéctalo cuando el celular ya este cargado.',
    aliases: ['cargador', 'celular', 'movil'],
    categoria: 'Informática',
    potencia_w: 5,
    horas_uso_dia: 2,
    orden: 22,
  },
  {
    nombre: 'Secadora de ropa',
    texto: 'Aprende a separar la ropa de acuerdo a la textura, el algodón necesitará más calor que la tela sintética, activa la opción de auto secado para que se apague apenas termine, mucho mejor sécalas al aire libre.',
    aliases: ['secadora'],
    categoria: 'Lavandería',
    potencia_w: 2000,
    horas_uso_dia: 1,
    orden: 23,
  },
  {
    nombre: 'Aspiradora',
    texto: 'No uses la aspiradora más de lo necesario, mantén limpios los filtros de la aspiradora y limpia regularmente su depósito. Si no lo haces, el motor se forzará más de lo necesario y consumirá más energía.',
    categoria: 'Hogar',
    potencia_w: 1400,
    horas_uso_dia: 0.5,
    orden: 24,
  },
  {
    nombre: 'Lavadora',
    texto: 'Solo lava cuando haya suficiente ropa para llenar tu lavadora, así aprovecharás al máximo. Además, no eches más detergente de lo necesario porque no mejorará el lavado, solo estarás utilizando más agua y electricidad para el enjuague.',
    categoria: 'Lavandería',
    potencia_w: 1500,
    horas_uso_dia: 1,
    modulo: 'aparato',
    orden: 25,
  },
];

const FANTASMA_DEFAULTS = [
  {
    nombre: 'Stand-by cargador',
    texto: 'Desconecte el cargador de la toma cuando no esté en uso; el consumo fantasma se acumula durante horas sin carga.',
    aliases: ['cargador stand-by', 'cargador celular stand-by'],
    categoria: 'Cargadores',
    potencia_w: 0.24,
    horas_uso_dia: 24,
    modulo: 'fantasma',
    orden: 1,
  },
  {
    nombre: 'Stand-by TV 37" LCD',
    texto: 'Desconecte el televisor o use una regleta con interruptor al final del día para eliminar el consumo en stand-by.',
    aliases: ['tv stand-by', 'televisor stand-by'],
    categoria: 'Televisores',
    potencia_w: 2,
    horas_uso_dia: 20,
    modulo: 'fantasma',
    orden: 2,
  },
  {
    nombre: 'Stand-by TV 42"',
    texto: 'Programe el apagado automático y desenchufe el equipo cuando cierre el local o vaya a dormir.',
    categoria: 'Televisores',
    potencia_w: 3,
    horas_uso_dia: 20,
    modulo: 'fantasma',
    orden: 3,
  },
  {
    nombre: 'Stand-by TDT',
    texto: 'El decodificador consume energía las 24 horas; apáguelo cuando no vea televisión.',
    aliases: ['decodificador', 'cable'],
    categoria: 'Televisores',
    potencia_w: 5,
    horas_uso_dia: 24,
    modulo: 'fantasma',
    orden: 4,
  },
  {
    nombre: 'Stand-by PC portatil',
    texto: 'Apague por completo la laptop y retire el cargador de la toma cuando termine de usarla.',
    aliases: ['laptop stand-by', 'portatil stand-by'],
    categoria: 'Electrodomésticos',
    potencia_w: 4,
    horas_uso_dia: 24,
    modulo: 'fantasma',
    orden: 5,
  },
  {
    nombre: 'Stand-by Equipo música',
    texto: 'Desconecte el equipo de sonido cuando no lo use; el modo espera consume energía de forma continua.',
    aliases: ['equipo de sonido stand-by', 'parlante stand-by'],
    categoria: 'Audio',
    potencia_w: 6,
    horas_uso_dia: 24,
    modulo: 'fantasma',
    orden: 6,
  },
  {
    nombre: 'Stand-by Alexa/Google',
    texto: 'Los asistentes inteligentes permanecen activos todo el día; desconéctelos en horarios de bajo uso.',
    aliases: ['alexa', 'google home', 'asistente inteligente'],
    categoria: 'Smart Home',
    potencia_w: 3,
    horas_uso_dia: 24,
    modulo: 'fantasma',
    orden: 7,
  },
  {
    nombre: 'Stand-by Microondas',
    texto: 'El reloj del microondas consume energía constantemente; desenchúfelo si solo lo usa ocasionalmente.',
    categoria: 'Electrodomésticos',
    potencia_w: 4,
    horas_uso_dia: 24,
    modulo: 'fantasma',
    orden: 8,
  },
  {
    nombre: 'Stand-by Radio despertador',
    texto: 'Use un despertador con batería o desconecte el equipo durante el día si no lo necesita.',
    categoria: 'Electrodomésticos',
    potencia_w: 7,
    horas_uso_dia: 24,
    modulo: 'fantasma',
    orden: 9,
  },
  {
    nombre: 'Stand-by Caldera de gas',
    texto: 'La caldera en espera mantiene circuitos activos; apáguela cuando no requiera calefacción.',
    categoria: 'Electrodomésticos',
    potencia_w: 3.5,
    horas_uso_dia: 20,
    modulo: 'fantasma',
    orden: 10,
  },
  {
    nombre: 'Stand-by Robot aspirador',
    texto: 'Desconecte la base de carga si el robot no se usará por varios días.',
    categoria: 'Electrodomésticos',
    potencia_w: 3,
    horas_uso_dia: 20,
    modulo: 'fantasma',
    orden: 11,
  },
  {
    nombre: 'Stand-by regletas',
    texto: 'Use regletas con interruptor y apáguelas por completo al salir o cerrar el local.',
    aliases: ['regleta', 'multicontacto'],
    categoria: 'Otros',
    potencia_w: 0.3,
    horas_uso_dia: 24,
    modulo: 'fantasma',
    orden: 12,
  },
];

const ILUMINACION_DEFAULTS = [
  {
    nombre: 'Bombillas incandescentes',
    texto: 'Reemplace las bombillas incandescentes por LED; consumen hasta un 80% menos energía con la misma iluminación.',
    aliases: ['incandescente', 'foco incandescente'],
    categoria: 'Incandescente',
    potencia_w: 100,
    horas_uso_dia: 6,
    modulo: 'iluminacion',
    orden: 1,
  },
  {
    nombre: 'Bombillas LED',
    texto: 'Prefiera bombillas LED certificadas; duren más y reducen notablemente el gasto mensual de iluminación.',
    aliases: ['led', 'foco led'],
    categoria: 'LED',
    potencia_w: 7,
    horas_uso_dia: 6,
    modulo: 'iluminacion',
    orden: 2,
  },
  {
    nombre: 'Culvilux o Splendor LED',
    texto: 'Use luminarias LED de buena eficiencia y apague las áreas que no estén en uso.',
    categoria: 'LED',
    potencia_w: 27,
    horas_uso_dia: 6,
    modulo: 'iluminacion',
    orden: 3,
  },
  {
    nombre: 'Lámparas LED',
    texto: 'Aproveche la luz natural durante el día y reduzca horas de encendido de lámparas interiores.',
    categoria: 'LED',
    potencia_w: 48,
    horas_uso_dia: 6,
    modulo: 'iluminacion',
    orden: 4,
  },
  {
    nombre: 'Reflectores Halógenos',
    texto: 'Evite reflectores halógenos en exteriores por largos periodos; considere reemplazarlos por LED de exterior.',
    aliases: ['reflector', 'halogeno'],
    categoria: 'Halógeno',
    potencia_w: 10,
    horas_uso_dia: 6,
    modulo: 'iluminacion',
    orden: 5,
  },
  {
    nombre: 'Spot LED',
    texto: 'Instale spots LED en zonas puntuales y utilice sensores de movimiento en pasillos o baños.',
    aliases: ['spot', 'downlight'],
    categoria: 'Spot LED',
    potencia_w: 18,
    horas_uso_dia: 6,
    modulo: 'iluminacion',
    orden: 6,
  },
];

const ALL_DEFAULTS = [
  ...DEFAULTS.map((item) => ({ ...item, modulo: item.modulo || 'aparato' })),
  ...FANTASMA_DEFAULTS,
  ...ILUMINACION_DEFAULTS,
];

const seedRecomendaciones = async () => {
  let created = 0;

  for (const item of ALL_DEFAULTS) {
    const [, wasCreated] = await Recomendacion.findOrCreate({
      where: { nombre: item.nombre, modulo: item.modulo },
      defaults: {
        ...item,
        activo: true,
      },
    });
    if (wasCreated) created += 1;
  }

  if (created > 0) {
    console.log(`✓ Recomendaciones iniciales: ${created} creadas`);
  }
};

module.exports = { seedRecomendaciones, DEFAULTS, FANTASMA_DEFAULTS, ILUMINACION_DEFAULTS };
